name    'inkblot/stanchion'
version '1.1.0'
source  'git://github.com/inkblot/puppet-stanchion'
author  'inkblot'
license 'Apache 2.0'
summary 'Stanchion serialization server'
description 'A Puppet module for setting up stanchion for RiakCS'
project_page 'https://github.com/inkblot/puppet-stanchion'

dependency 'inkblot/riak', '>= 1.0.0'
dependency 'inkblot/riakcs', '>= 1.1.0'
